LAB2/QLBanSach/Controllers/BookStoreController.cs
using QLBanSach.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLBanSach.Controllers
{
    public class BookStoreController : Controller
    {
        // GET: BookStore
        QLBanSachEntities data = new QLBanSachEntities();
        
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        
        public ActionResult Index()
        {
            var sachMoi = LaySachMoi(5);
            return View(sachMoi);
        }
        public ActionResult ChuDe()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult NhaXuatBan()
        {
            var nxb = from cd in data.NHAXUATBANs select cd;
            return PartialView(nxb);
        }
        public ActionResult SPTheochude(int MaCD)
        {
            var sach = from s in data.SACHes where s.CHUDE.MaCD == MaCD select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int MaNXB)
        {
            var sach = from s in data.SACHes where s.MaNXB == MaNXB select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;

            return View(sach.Single());
        }
        public ActionResult SignUp()
        {
            return View();
        }
    }
}

LAB2/QLBanSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LAB2/QLBanSach/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Electronix Store</title>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" />
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="iecss.css" />
    <![endif]-->
    <script type="text/javascript" src="~/Scripts/boxOver.js"></script>
</head>

<body>
    <div id="main_container">
        <div class="top_bar">
            <div class="top_search">
                <div class="search_text"><a href="http://all-free-download.com/free-website-templates/">Advanced Search</a></div>
                <input type="text" class="search_input" name="search" />
                <input type="image" src="~/Content/Images/search.gif" class="search_bt" />
            </div>
            <div class="languages">
                <div class="lang_text">Languages:</div>
                <a href="http://all-free-download.com/free-website-templates/" class="lang"><img src="~/Content/Images/en.gif" alt="" border="0" /></a> <a href="http://all-free-download.com/free-website-templates/" class="lang"><img src="images/de.gif" alt="" border="0" /></a>
            </div>
        </div>

        <div id="header">
            <div id="logo"> <a href="http://all-free-download.com/free-website-templates/"><img src="~/Content/Images/logo.png" alt="" border="0" width="237" height="140" /></a> </div>
            <div class="oferte_content">
                <div class="top_divider"><img src="~/content/Images/header_divider.png" alt="" width="1" height="164" /></div>
                <div class="oferta">
                    <div class="oferta_content">
                        <img src="~/Content/Images/laptop.png" width="94" height="92" alt="" border="0" class="oferta_img" />
                        <div class="oferta_details">
                            <div class="oferta_title">Samsung GX 2004 LM</div>
                            <div class="oferta_text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </div>
                            <a href="details.html" class="details">details</a>
                        </div>
                    </div>
                    <div class="oferta_pagination"> <span class="current">1</span> <a href="http://all-free-download.com/free-website-templates/">2</a> <a href="http://all-free-download.com/free-website-templates/">3</a> <a href="http://all-free-download.com/free-website-templates/">4</a> <a href="http://all-free-download.com/free-website-templates/">5</a> </div>
                </div>
                <div class="top_divider"><img src="~/Content/Images/header_divider.png" alt="" width="1" height="164" /></div>
            </div>
            <!-- end of oferte_content-->
        </div>
        <div id="menu_tab">
            <div class="left_menu_corner"></div>
            <ul class="menu">
                <li><a href="@Url.Action("Index","BookStore")" class="nav1"> Home</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("Index","BookStore")" class="nav2">Products</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("Index","BookStore")" class="nav3">Specials</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("Index","BookStore")" class="nav4">My account</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("Dangky","nguoidung")" class="nav4">Sign Up</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("Index","BookStore")" class="nav5">Shipping</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("Index","BookStore")" class="nav6">Contact Us</a></li>
                <li class="divider"></li>
            </ul>
            <div class="right_menu_corner"></div>
        </div>
        <div class="left_content">
            <div class="title_box">Chủ đề</div>

                @Html.Action("ChuDe", "BookStore")


        </div>
        <div class="center_content">
            @RenderBody()
        </div>
        <div class="right_content">
            <div class="shopping_cart">
                <div class="cart_title">Giỏ hàng</div>
                <div class="cart_details">
                    @ViewBag.Tongsoluong sản phẩm <br />
                    <span class="border_cart"></span> Tổng: <span class="price"> @ViewBag.Tongtien VNĐ</span>
                </div>
                <div class="cart_icon"><a href="@Url.Action("Giohang","Giohang")" title="header=[Checkout] body=[&nbsp;] fade=[on]"><img src="~/Content/Images/shoppingcart.png" alt="" width="48" height="48" border="0" /></a></div>
            </div>
            <div class="title_box">Nhà xuất bản</div>
            @Html.Action("NhaXuatBan", "BookStore")

        </div>
        <div class="footer">
            <div class="left_footer"> <img src="~/Content/Images/footer_logo.png" alt="" width="170" height="49" /> </div>
            <div class="center_footer">
                Template name. All Rights Reserved 2008<br />
                <a href="http://csscreme.com"><img src="~/Content/Images/csscreme.jpg" alt="csscreme" border="0" /></a><br />
                <img src="~/Content/Images/payment.gif" alt="" />
            </div>
            <div class="right_footer"> <a href="http://all-free-download.com/free-website-templates/">home</a> <a href="http://all-free-download.com/free-website-templates/">about</a> <a href="http://all-free-download.com/free-website-templates/">sitemap</a> <a href="http://all-free-download.com/free-website-templates/">rss</a> <a href="contact.html">contact us</a> </div>
        </div>
    </div>
</body>
</html>